server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Fun-Team-UPC/ILanguage-config-data.git
          searchPaths:
          username: ${GIT_USER}
          password: ${TOKEN}
          

  security:
    user:
      name: root
      password: s3cr3t
