server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/Fun-Team-UPC/spring-cloud-config-data
  security:
    user:
      name: root
      password: s3cr3t